In [1]:
import os, sys

pysbf_path = "/media/Data/Home/PanStarrs/Jan/HI/augment/SBF/codes/"
sys.path.insert(0, pysbf_path)
from pysbf import *

In [2]:
import astropy.io.fits as fits
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pylab as py

In [3]:
def xcmd(cmd,verbose):

    if verbose: print('\n'+cmd)

    tmp=os.popen(cmd)
    output=''
    for x in tmp: output+=x
    if 'abort' in output:
        failure=True
    else:
        failure=tmp.close()
    if False:
        print('execution of %s failed' % cmd)
        print('error is as follows',output)
        sys.exit()
    else:
        return output
    
from contextlib import contextmanager
import os

@contextmanager
def cwd(path):
    oldpwd = os.getcwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(oldpwd)
        
        
class cd:
    """Context manager for changing the current working directory"""
    def __init__(self, newPath):
        self.newPath = os.path.expanduser(newPath)

    def __enter__(self):
        self.savedPath = os.getcwd()
        os.chdir(self.newPath)

    def __exit__(self, etype, value, traceback):
        os.chdir(self.savedPath)

In [48]:
def add_hdr(hdr, header, key):
    
    value = header[key]
    
    if isinstance(value, str):
        value = "'" + value + "'"
    else:
        value = str(value)
    
    hdr += key + "=" + value + " / " + header.comments[key] + "\n"
    
    return hdr

In [5]:
def getPGCid(objname):
    """extracting the PGC ID of a galaxy given its name

    Args:
        objname  (str): galaxy name

    Returns:
        int: PGC ID
    """

    
    my_url = 'http://ned.ipac.caltech.edu/cgi-bin/nph-objsearch?objname='+objname+'&extend=no&of=xml_names&extend=no&hconst=73&omegam=0.27&omegav=0.73&corr_z=1&out_csys=Equatorial&out_equinox=J2000.0&obj_sort=RA+or+Longitude&of=pre_text&zv_breaker=30000.0&list_limit=5&img_stamp=YES'
    tag = mySoup(my_url).findAll('a', href="/cgi-bin/catdef?prefix=PGC")[0].parent
    pgc = int(str(tag).split("</a>")[1].split('</td>')[0].strip())
   
    return pgc

In [6]:
def addGalaxyInfo(Leda, pgc, response=None, objname=None):
    """Exctracting the information of a galaxy from the LEDA catalog 
    given the corresponsing PGC ID

    :param Leda: Leda catalog
    :type Leda: ``Pandas dataFrame``
    :param pgc: pgc ID
    :type pgc: ``int``
    :param response: response to be modified, defaults to None
    :type response: python ``dictionary``, optional
    :param objname: galaxy name, defaults to None
    :type objname: ``str``, optional
    :return: response dictionary that holds the requested galaxy information
    :rtype: python dictionary
    """

    if response is None:
        response = {}

    myGalaxy = Leda.loc[int(pgc)]
    response["pgc"]     = pgc
    response["ra"]      = "%.4f"%((myGalaxy.al2000)*15)         # deg
    response["dec"]     = "%.4f"%(myGalaxy.de2000)              # deg
    response["fov"]     = "%.2f"%(1.5*0.1*10**myGalaxy.logd25)  # arcmin
    response["pa"]      = str(myGalaxy.pa)

    if objname is None:
        response["objname"] = str(myGalaxy.objname)
    else:
        response["objname"] = objname

    return response

In [7]:
def loadLeda(leda_catalog):
    """Loading the HyperLeda catalog: 
    - http://leda.univ-lyon1.fr/
    - This catalog tabulates the proper information on local galaxies

    :return: the Leda catalog in the Pandas dataFrame format
    :rtype: Pandas ``dataFrame``
    """

    df = pd.read_csv(leda_catalog, delimiter=',')
    df = df.rename(columns=lambda x: x.strip())
                   
    return df.set_index('PGC')

In [22]:
Leda = loadLeda("LEDA.csv")

Leda.head()

<ipython-input-22-a7ac7fd79853>:1: DtypeWarning: Columns (71,73,74) have mixed types.Specify dtype option on import or set low_memory=False.
  Leda = loadLeda("LEDA.csv")

,al1950,de1950,al2000,de2000,l2,b2,sgl,sgb,t,e_t,...,objname,objtype,type,bar,ring,multiple,compactness,angclass,RA2000,DEC2000
PGC,,,,,,,,,,,,,,,,,,,,,
1,23.95695,0.42327,23.99966,0.70168,96.87946,-59.54180,293.35019,13.43002,2.4,5.0,...,PGC000001,G,S?,NaN,NaN,NaN,NaN,NaN,235958.8,4206.0
2,23.95786,46.99616,0.00047,47.27450,113.95535,-14.69916,341.64403,20.73880,3.1,0.4,...,UGC12889,G,Sb,B,NaN,NaN,NaN,NaN,1.7,471628.2
4,23.95829,22.80927,0.00096,23.08764,107.83219,-38.27289,316.05865,18.45140,5.0,1.2,...,PGC000004,G,Sc,NaN,NaN,NaN,NaN,NaN,3.5,230515.5
5,23.95988,32.46003,0.00254,32.73839,110.62060,-28.90431,326.17705,19.78055,-0.6,1.2,...,IC5370,G,S0-a,NaN,NaN,NaN,NaN,NaN,9.1,324418.2
6,23.95790,15.60327,0.00058,15.88165,105.25252,-45.21822,308.62424,17.10314,-1.0,2.0,...,PGC000006,G,S0-a,NaN,NaN,NaN,C,NaN,2.1,155253.9

In [32]:
def load_info(galaxy_name):
    
    ned = get_ned_info([galaxy_name])
    
    try:
        if ned is not None:
            objName = ned.iloc[0]["Object Name"]
            ra, dec = ned.iloc[0]["ra_dec"]

            pgc = getPGCid(objName.replace(" ", "%20"))
            logd25 = Leda.loc[pgc]["logd25"]
            
            return pgc, objName.replace(" ", ""), ra, dec, logd25
    except: 
        print(f"Couldn't load data for {galaxy_name} ... !")
        pass
        
    return None

In [ ]:
# example of available products for each brick

# https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/south/coadd/161/1610m107/

In [8]:
# ra = 194.3283 # 194.1825
# dec = 21.682

In [160]:
# d25 = 10**1.66
# pgc = 13318
# ra = 3.6076600  * 15.
# dec = -34.9761300 
# objNAME = 'NGC1380'


# d25 = 10**1.93
# pgc = 13418
# ra = 3.6414100 * 15.
# dec = -35.4506300
# objNAME = 'NGC1399'

d25 = 10**1.70
pgc = 13433
ra = 3.6477500  * 15.
dec = -35.5942400
objNAME = 'NGC1404'

In [52]:
def get_decam(bricks, pgc, objName, ra, dec, logd25):

    temp_repo_name = "DECam/" + objName

    d25 = 10**logd25
    size = 0.1 * d25 / 60  # deg
    delta = size * 8
    pix_size = 0.262   # arcsec
    
    
    naxis = int(6*size*3600 / pix_size)
    
    if naxis > 5000:
        naxis = 5000
    else:
        return

    ra_max  =  ra+delta
    ra_min  =  ra-delta
    dec_max =  dec+delta
    dec_min =  dec-delta


    dg = bricks[(bricks["RA1"]<ra_max) & 
       (bricks["RA2"]>ra_min) &
       (bricks["DEC1"]<dec_max) & 
       (bricks["DEC2"]>dec_min) 
      ]



    if not os.path.isdir(temp_repo_name):
        os.mkdir(temp_repo_name)

    for filt in ["g", "r", "i", "z"]:

        urls = [] 
        for iid in dg.BRICKNAME.values:

            s = str(iid)[2:-1]

            base_url = f"https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr10/south/coadd/{s[:3]}/{s}/"
            image_name = f"legacysurvey-{s}-image-{filt}.fits.fz"
            url = base_url + image_name

            urls.append(url)

        with cwd(temp_repo_name):


            for url in urls:
                xcmd(f"wget {url}", verbose=False)


            cmd = 'mkdir tmp'
            xcmd(cmd, False)

            for url in urls:

                fname = url.split("/")[-1].split(".")[0]
                hdulist = fits.open(fname+".fits.fz")
                prihdr = hdulist[1].header 

                fits.writeto('tmp/' + fname+'.fits', hdulist[1].data, header=hdulist[1].header, 
                                        output_verify='exception', overwrite=True, checksum=False)


                fout=open('montage.csh','w')

            montage = '''
              rm *tbl
              rm -rf projected
              mkdir  projected
              mImgtbl tmp rimages.tbl
              mProjExec -p tmp rimages.tbl tmp.hdr projected stats.tbl
              mImgtbl projected pimages.tbl
              mAdd -p projected pimages.tbl tmp.hdr tmp.fits
              mConvert -b -32 tmp.fits tmp.fits
              rm *area*fits
              rm *tbl
              rm -rf projected
              '''

            fout.write(montage+'\n')
            fout.close()

            crpix = naxis/2
            hdr = ''
            hdr += 'SIMPLE = T' + '\n'
            hdr += 'BITPIX = -32' + '\n'
            hdr += 'NAXIS = 2' + '\n'
            hdr += 'NAXIS1 = '+str(naxis) + '\n'
            hdr += 'NAXIS2 = '+str(naxis) + '\n'
            hdr += 'CTYPE1 = \'RA---TAN\'' + '\n'
            hdr += 'CTYPE2 = \'DEC--TAN\'' + '\n'
            hdr += 'CRVAL1 = ' +str(ra)+ '\n'
            hdr += 'CRVAL2 = ' +str(dec)+ '\n'
            hdr += 'CRPIX1 = '+str(crpix) + '\n'
            hdr += 'CRPIX2 = '+str(crpix) + '\n'
            hdr += 'CDELT1 = -7.27777778E-05' + '\n'
            hdr += 'CDELT2 = 7.27777778E-05' + '\n'
            hdr += 'CROTA2 = 0.000000' + '\n'
            hdr += 'EQUINOX = 2000.0' + '\n'
            hdr += 'BSCALE = 1' + '\n'
            hdr += 'BZERO = 0' + '\n'
            hdr += 'EXPTIME = 1.0' + '\n'
#             hdr += 'ZP = 16.40006562 ' + '\n'
            hdr = add_hdr(hdr, prihdr, "MAGZERO")
            hdr = add_hdr(hdr, prihdr, "BUNIT")
            hdr = add_hdr(hdr, prihdr, "COSKY_"+filt.upper())
            hdr = add_hdr(hdr, prihdr, "FILTER")
            hdr = add_hdr(hdr, prihdr, "FILTERX")
            hdr = add_hdr(hdr, prihdr, "INSTRUME")
            hdr = add_hdr(hdr, prihdr, "TELESCOP")
            hdr = add_hdr(hdr, prihdr, "OBSERVAT")
            hdr = add_hdr(hdr, prihdr, "EQUINOX")
            hdr = add_hdr(hdr, prihdr, "LSDR")
            hdr = add_hdr(hdr, prihdr, "SURVEY")
            hdr = add_hdr(hdr, prihdr, "SURVEYID")
            hdr = add_hdr(hdr, prihdr, "LEGPIPEV")
        #     hdr = add_hdr(hdr, prihdr, "")
        #     hdr = add_hdr(hdr, prihdr, "")

            hdr += 'PGC = ' + 'PGC'+str(pgc) + '\n'
            hdr += 'OBJECT = ' + objName + '\n'
            hdr += 'HISTORY = \'email: <ehsan20@hawaii.edu>\'' + '\n'  
            hdr += 'END' + '\n'

            fout=open('tmp.hdr','w')
            fout.write(hdr)
            fout.close()

            xcmd('csh montage.csh', False)
            xcmd('rm montage.csh', False)
            xcmd('rm tmp.hdr', False)
            xcmd('rm -rf tmp', False)
            xcmd('rm -rf *.fits.fz*', False)
            xcmd(f'mv tmp.fits {objName}_{filt}.fits', True)

In [50]:
from astropy.table import Table

data = Table.read('survey-bricks.fits', format='fits')
bricks = data.to_pandas()

In [69]:

galaxies = [
# "IC3025",
# "IC3032",
# "IC3487",
# "IC3586",
# "N4458",
"N4472",
"N4489",
"N4649",
]

In [70]:
# for galaxy in ["IC1919", "IC2006", "N1344", "N1374", "N1375"]:
for galaxy in galaxies:


    pgc, objName, ra, dec, logd25 = load_info(galaxy)
    
    
    
    get_decam(bricks, pgc, galaxy, ra, dec, logd25)

mv tmp.fits N4472_g.fits

mv tmp.fits N4472_r.fits

mv tmp.fits N4472_i.fits

mv tmp.fits N4472_z.fits

mv tmp.fits N4489_g.fits

mv tmp.fits N4489_r.fits

mv tmp.fits N4489_i.fits

mv tmp.fits N4489_z.fits

mv tmp.fits N4649_g.fits

mv tmp.fits N4649_r.fits

mv tmp.fits N4649_i.fits

mv tmp.fits N4649_z.fits

In [57]:
def has_decam(bricks, galaxy_name):

    pgc, objName, ra, dec, logd25 = load_info(galaxy_name)

    d25 = 10**logd25
    size = 0.1 * d25 / 60  # deg
    delta = size * 8
    pix_size = 0.262   # arcsec
    naxis = int(6*size*3600 / pix_size)

    ra_max  =  ra+delta
    ra_min  =  ra-delta
    dec_max =  dec+delta
    dec_min =  dec-delta


    dg = bricks[(bricks["RA1"]<ra_max) & 
       (bricks["RA2"]>ra_min) &
       (bricks["DEC1"]<dec_max) & 
       (bricks["DEC2"]>dec_min) 
      ]
    
    
    return dg.shape[0]

In [66]:
has_decam(bricks, "NGC4649")

,BRICKNAME,BRICKID,BRICKQ,BRICKROW,BRICKCOL,RA,DEC,RA1,RA2,DEC1,DEC2
392732,b'1900p107',392733,3,403,747,190.042373,10.75,189.915254,190.169492,10.625,10.875
392733,b'1902p107',392734,2,403,748,190.296610,10.75,190.169492,190.423729,10.625,10.875
392734,b'1905p107',392735,3,403,749,190.550847,10.75,190.423729,190.677966,10.625,10.875
392735,b'1908p107',392736,2,403,750,190.805085,10.75,190.677966,190.932203,10.625,10.875
392736,b'1910p107',392737,3,403,751,191.059322,10.75,190.932203,191.186441,10.625,10.875
...,...,...,...,...,...,...,...,...,...,...,...
402619,b'1908p125',402620,0,410,746,190.866477,12.50,190.738636,190.994318,12.375,12.625
402620,b'1911p125',402621,1,410,747,191.122159,12.50,190.994318,191.250000,12.375,12.625
402621,b'1913p125',402622,0,410,748,191.377841,12.50,191.250000,191.505682,12.375,12.625
402622,b'1916p125',402623,1,410,749,191.633523,12.50,191.505682,191.761364,12.375,12.625
402623,b'1918p125',402624,0,410,750,191.889205,12.50,191.761364,192.017045,12.375,12.625